cms/Controllers/GDataController.cs
using System;
using System.Web.Mvc;
using Google.GData.Client;
using cms.Code;
using cms.Code.LinkAccounts;

namespace cms.Controllers
{
	[Authorize(Roles = "admin")]
	public class GDataController : CmsControllerBase
	{
		private Func<GoogleDataOAuth2Service> _gdataAuthFnc;
		private GoogleDataOAuth2Service GdataAuth { get; set; }

		protected override void OnActionExecuting(ActionExecutingContext filterContext)
		{
			GdataAuth = _gdataAuthFnc.Invoke();
			if (GdataAuth.IsAuhtorized() && !GdataAuth.IsValid())
			{
				try
				{
					GdataAuth.RefreshAccessToken();
				}
				catch (Exception ex)
				{
					
				}
			}
		}

		protected override void Initialize(System.Web.Routing.RequestContext requestContext)
		{
			base.Initialize(requestContext);
			_gdataAuthFnc = () => new GoogleDataOAuth2Service(OAuth2ParametersStorageFactory.StorageDatabase(SessionProvider));
		}

		public ActionResult Index()
		{
			return View(_gdataAuthFnc.Invoke());
		}

		[HttpPost]
		public ActionResult RedirectToAuthenticate(OAuth2Parameters model)
		{
			GdataAuth.Storage.Parameters = model;

			var u = HttpContext.Request.Url;
			
			GdataAuth.Storage.Parameters.RedirectUri = string.Format("{0}://{1}/GdataAuth/Authenticate", u.Scheme, u.Authority);
			GdataAuth.Storage.Parameters.State = ApplicationId.ToString();

			return Redirect(GdataAuth.OAuth2AuthorizationUrl());
		}

		[HttpGet]
		public ActionResult Authenticate(string code)
		{
			GdataAuth.Storage.Parameters.AccessCode = code;
			var u = HttpContext.Request.Url;
			
			GdataAuth.Storage.Parameters.RedirectUri = string.Format("{0}://{1}/GdataAuth/Authenticate", u.Scheme, u.Authority);
			
			GdataAuth.GetAccessToken();
			if (GdataAuth.IsAuhtorized())
			{
				TempData["message"] = "Úspěšně připojeno na Google Picasa.";
			}
			return RedirectToAction("Index");
		}
	
		[HttpPost]
		public ActionResult Revoke(string code)
		{
			GdataAuth.RevokeToken();
			return RedirectToAction("Index");
		}
		
		[HttpGet]
		public ActionResult RefreshToken()
		{
			GdataAuth.RefreshAccessToken();
			return RedirectToAction("Index");
		}
	}

	public enum ViewStatus
	{
		Success,
		Error,
		Info

	}
}

cms/Controllers/SettingsController.cs
using System.Web.Mvc;
using cms.Code;

namespace cms.Controllers
{
	[Authorize(Roles = "admin")]
	public class SettingsController : CmsControllerBase
	{
		public ActionResult Index()
		{
			return View();
		}

	}
}

cms/Views/GData/GdataPhotosSettins.cshtml
<div ng-controller="GdataPhotosSettings">

</div>

cms/Views/GData/Index.cshtml
@using cms.Code.LinkAccounts
@model GoogleDataOAuth2Service

@{
	Layout = "../_AdminTemplates/_Layout_Appllication.cshtml";
    ViewBag.Title = ViewBag.ApplicationName + " - administrace ";
}

<style>
	.xxx h3, .xxx h5
	{
		margin: 0px;
		padding: 0px;
	}

	.xxx h3
	{
		line-height: 28px;
	}

	.xxx span
	{
		color: gray;
	}

	.xxx:hover span
	{
		color: gray;
	}
</style>


<h3>propojení se vzdálenými službami</h3>
@if (!string.IsNullOrEmpty(TempData["message"] as string))
{
	<div class="alert alert-success">
		@TempData["message"]
		<button type="button" class="close" data-dismiss="alert">&times;</button>
	</div>
}


@switch (Model.GetStatus())
{
	case GoogleDataOAuth2Status.Authorized:
	<div>
		<table style="width: 100%">
			<tr>
				<td>
					<img src="@Url.Content("~/Content/images/picasa.png")"/>
				</td>
				<td>
					@using (Html.BeginForm("Revoke", "GData"))
	 {
						<button class="btn btn-danger btn-large" type="submit">zrušit přístup</button>
							    
	 }
				</td>
			</tr>

		</table>

		@Html.Partial("GdataPhotosSettins")

	</div>
	 break;

	case GoogleDataOAuth2Status.NotAuthorized:
	 Html.RenderPartial("Index_NotAuthorized", Model.Storage.Parameters);
	 break;

	case GoogleDataOAuth2Status.NeedRefresh:
	 Html.RenderPartial("Index_ReAuthorize", Model);
	 break;
}

<h3>@Html.ActionLink("Nastavení velikostí náhledů", "Index", "Settings")</h3>

cms/Views/GData/Index_NotAuthorized.cshtml
@model Google.GData.Client.OAuth2Parameters


<div ng-app>
	@using (Html.BeginForm("RedirectToAuthenticate", "GData", FormMethod.Post, new { @class = "form-horizontal" }))
 {
		@Html.AntiForgeryToken()

		@Html.HiddenFor(m => m.ClientId, new { @class = "input-block-level" })
		@Html.HiddenFor(m => m.ClientSecret, new { @class = "input-block-level" })
		@Html.HiddenFor(m => m.RedirectUri, new { @class = "input-block-level" })
		@Html.HiddenFor(m => m.Scope)

		<table style="width: 100%">
			<tr>
				<td style="width: 60px">
					<img src="@Url.Content("~/Content/images/picasa_logo.png")"/>
				</td>
				<td class="xxx">
					<h3>Google Picasa</h3>
					<span>synchronizujte fotky z webových alb Picasa od Googlu</span>
				</td>

				<td>
					@using (Html.BeginForm("Revoke", "GData"))
	 {
						<button class="btn btn-success btn-large" type="submit">připojit</button>
							    
	 }
				</td>

			</tr>

		</table>
        
 }

</div>

cms/Views/GData/Index_ReAuthorize.cshtml
@model cms.Code.LinkAccounts.GoogleDataOAuth2Service

@*<div>Připojení na Google Data nefunguje jak má. Je potřeba resetovat propojení a provést autorizaci znovu.</div>
@using (Html.BeginForm("Revoke", "GData", FormMethod.Post, new { @class = "form-horizontal" }))
{
	<button class="btn btn-danger btn-large" type="submit">zrušit propojení</button>
							    
}*@
<table style="width: 100%">
	<tr>
		<td >
			@using (Html.BeginForm("Revoke", "GData", FormMethod.Post, new { @class = "form-horizontal" }))
   {
				<button class="btn btn-danger btn-large" type="submit">zrušit propojení</button>
							    
   }
		</td>
		<td class="xxx alert alert-error">
			<h3 class="">Chyba</h3>
		    <span class="text-error">Připojení na Google Data nefunguje jak má. Je potřeba resetovat propojení a provést autorizaci znovu.
                Resetovat připojení manuálně <a href="https://accounts.google.com/b/0/IssuedAuthSubTokens" target="_blank">zde</a></span>
		</td>
	</tr>

</table>

cms/Views/GData/Settings.cshtml
@{
	Layout = "../_AdminTemplates/_Layout_Appllication.cshtml";
    ViewBag.Title = ViewBag.ApplicationName + " - administrace ";
}

<h2>Settings</h2>